### ISSUE TITLE
Fluttercon 2024 support

### ISSUE THREAD

**Issue by Markus43** [rohan20/fluttercon#21]
Found your app when searching for a companion app for fluttercon 2024. Are you planning to support that event? If no: Do you have any quick hints how to customize this app, in order to make it work for fluttercon 2024?

**Comment by rohan20** [comment]
Hey @Markus43, sorry for the late response, I don't know why but I don't get notifications for issues created on this repository 😞 

I'm afraid I did not get access to the API this time around to make the app work for Fluttercon Berlin 2024. If I did, I would've added support. 

Hopefully next year! 🤞

> Do you have any quick hints how to customize this app, in order to make it work for fluttercon 2024?

1. Add sessionize API URL (you'd need to get this from the conference's organizers) to `conference_secrets.dart` under `lib/src` (gitignored)
2. Change a few hardcoded values

That's it 😃 

I'm adding support for Fluttercon USA 2024, so you should see a PR doing exactly this soon.
